config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :articles
    resources :article_categories
  end
  mount Fae::Engine => '/admin'

    resources :articles
    resources :article_categories
end

app/models/about_us_page.rb
class AboutUsPage < Fae::StaticPage

  @slug = 'about_us'

  # required to set the has_one associations, Fae::StaticPage will build these associations dynamically
  def self.fae_fields
    {
      hero_image: { type: Fae::Image },
      headline: { type: Fae::TextField },
      body: { type: Fae::TextArea }
    }
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  include Fae::BaseModelConcern

  validates :title, presence: true
  validates :slug, Fae.validation_helpers.slug


  def fae_display_field
    title
  end

  has_fae_file :pdf

  has_fae_image :hero_image


  belongs_to :article_category
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  include Fae::BaseModelConcern

  def fae_display_field
    name
  end


  acts_as_list add_new_at: :top
  default_scope { order(:position) }

end

app/models/concerns/fae/authorization_concern.rb
module Fae
  module AuthorizationConcern
    extend ActiveSupport::Concern
    module ClassMethods

      # Use the access_map to define any controllers that need any special authorization
      # Fae comes with three default roles:
      # - super admin: CRUD all objects, INCLUDING users and root settings
      # - admin: CRUD all objects, INCLUDING users and EXCLUDING root settings
      # - users: CRUD all objects, EXCLUDING users and root settings

      # each item should have a string key of the plural controller name and
      # an array of role names for the value
      # use "content_blocks/#{page_name}" for content blocks

      # example:
      # {
      #  'people' => ['super admin', 'admin'],
      #  'content_blocks/about_us' => ['super admin']
      # }
      def access_map
        {}
      end

    end
  end
end

app/models/concerns/fae/navigation_concern.rb
module Fae
  module NavigationConcern
    extend ActiveSupport::Concern

    # define the navigation structure in this file
    # example structure:
    #
    # def structure
    #   [
    #     item('Top Nav Item 1', subitems: [
    #       item('Top Nav Dropdown Item 1', class: 'custom-class', path: some_named_route_path),
    #       item('Top Nav Dropdown Item 2', subitems: [
    #         item('Side Nav Item 1', subitems: [
    #           item('Side Nav Nested Item', path: some_named_route_path)
    #         ]),
    #         item('Side Nav Item 1', path: some_named_route_path)
    #       ]),
    #     ]),
    #     item('Pages', subitems: [
    #       item('Home', path: fae.edit_content_block_path('home')),
    #       item('About Us', path: fae.edit_content_block_path('about_us'))
    #     ])
    #   ]
    # end

    def structure
      [
        item('Article Categories', path: admin_article_categories_path),
        item('Articles', path: admin_articles_path),
        # scaffold inject marker
      ]
    end

  end
end

app/controllers/admin/article_categories_controller.rb
module Admin
  class ArticleCategoriesController < Fae::BaseController

  end
end

app/controllers/admin/articles_controller.rb
module Admin
  class ArticlesController < Fae::BaseController

    private

    def build_assets
      @item.build_hero_image if @item.hero_image.blank?
      @item.build_pdf if @item.pdf.blank?
    end

  end
end

app/controllers/admin/content_blocks_controller.rb
module Admin
  class ContentBlocksController < Fae::StaticPagesController

    private

    def fae_pages
      [AboutUPage]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article
  layout :set_layout

  def index
      @articles = Article.all
  end
  #
  def show
    @article = Article.find(params[:id])
  end

  private

    def build_assets
      @item.build_hero_image if @item.hero_image.blank?
      @item.build_pdf if @item.pdf.blank?
    end

    def set_layout
      'frontend'
    end

    def set_article
      @article = Article.find(params[:id])
    end

    def article_params
      params.require(:article).permit(:title )
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/article_categories/_form.html.slim
= simple_form_for(['admin', @item]) do |f|
  header.content-header.js-content-header
    == render 'fae/shared/form_header', header: @klass_name
  == render 'fae/shared/errors'

  main.content
    = fae_input f, :name

app/views/admin/article_categories/edit.html.slim
== render 'form'

app/views/admin/article_categories/index.html.slim
== render 'fae/shared/index_header', title: @klass_humanized.pluralize.titleize

main.content
  table.js-sort-row
    thead
      tr
        th.th-sortable-handle
        th Name
        th.-action-wide Modified
        th.-action data-sorter="false"

    tbody
      - if @items.present?
        - @items.each do |item|
          tr id=fae_sort_id(item)
            td.sortable-handle: i.icon-sort
            td = link_to item.fae_display_field, edit_admin_article_category_path(item)
            td = fae_date_format item.updated_at
            td = fae_delete_button item
      - else
        tr: td colspan="4" No items found

app/views/admin/article_categories/new.html.slim
== render 'form'

app/views/admin/articles/_form.html.slim
= simple_form_for(['admin', @item]) do |f|
  header.content-header.js-content-header
    == render 'fae/shared/form_header', header: @klass_name
  == render 'fae/shared/errors'

  main.content
    = fae_input f, :title, input_class: 'slugger'
    = fae_input f, :slug
    = fae_input f, :introduction
    = fae_input f, :body, markdown: true
    = fae_input f, :date

    = fae_association f, :article_category

    = fae_image_form f, :hero_image
    = fae_file_form f, :pdf

app/views/admin/articles/edit.html.slim
== render 'form'

app/views/admin/articles/index.html.slim
== render 'fae/shared/index_header', title: @klass_humanized.pluralize.titleize

main.content
  table.js-sort-column
    thead
      tr
        th Title
        th.-action-wide Modified
        th.-action data-sorter="false"

    tbody
      - if @items.present?
        - @items.each do |item|
          tr id=fae_sort_id(item)
            td = link_to item.fae_display_field, edit_admin_article_path(item)
            td = fae_date_format item.updated_at
            td = fae_delete_button item
      - else
        tr: td colspan="3" No items found

app/views/admin/articles/new.html.slim
== render 'form'

app/views/admin/content_blocks/about_us.html.slim
= simple_form_for @item, url: fae.update_content_block_path(slug: @item.slug), method: :put do |f|
  header.content-header.js-content-header
    == render 'fae/shared/form_header', header: @item

  main.content
    = fae_input f, :title

    = fae_image_form f, :hero_image
    = fae_content_form f, :headline
    = fae_content_form f, :body

app/views/articles/index.html.slim
- if @articles.present?
  - @articles.each do |article|
      td = link_to article.title, article_path(article)
      td = article.updated_at
- else
  tr: td colspan="3" No items found

app/views/articles/show.html.slim
  - @article.title

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tthatv</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/frontend.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Tthatv</title>
        <%= stylesheet_link_tag    'frontend/application', media: 'all', 'data-turbolinks-track' => true %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
        <%= csrf_meta_tags %>
    </head>
    <body>

        <%= yield %>

    </body>
</html>